WITH RECURSIVE ECOLI_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT  F.ID, F.PARENT_ID, S.GENERATION + 1
    FROM ECOLI_DATA AS F JOIN ECOLI_GEN AS S ON F.PARENT_ID = S.ID 
)

SELECT ID
FROM ECOLI_GEN
WHERE GENERATION = 3
ORDER BY ID