WITH TOTAL_AMOUNT AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT DISTINCT(P.PRODUCT_CODE), P.PRICE * T.TOTAL AS SALES
FROM PRODUCT AS P
JOIN OFFLINE_SALE AS O ON P.PRODUCT_ID = O.PRODUCT_ID
JOIN TOTAL_AMOUNT AS T ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE