WITH TARGET_ANIMAL AS (
    SELECT F.ANIMAL_ID, F.NAME, 
        RANK() OVER (ORDER BY DATEDIFF(S.DATETIME, F.DATETIME) DESC) AS ANIMAL_RANK
    FROM ANIMAL_INS AS F JOIN ANIMAL_OUTS AS S ON F.ANIMAL_ID = S.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM TARGET_ANIMAL
WHERE ANIMAL_RANK <= 2
ORDER BY ANIMAL_RANK ASC