WITH RANKED_REST AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        RANK () OVER (
            PARTITION BY FOOD_TYPE
            ORDER BY FAVORITES DESC
        ) AS REST_RANK
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM RANKED_REST
WHERE REST_RANK = 1
ORDER BY FOOD_TYPE DESC