WITH TEMP AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUARTILE_GROUP
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN QUARTILE_GROUP = 1 THEN 'CRITICAL'
        WHEN QUARTILE_GROUP = 2 THEN 'HIGH'
        WHEN QUARTILE_GROUP = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM TEMP
ORDER BY ID