WITH TARGET_USER AS (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)

SELECT S.USER_ID, S.NICKNAME,
    CONCAT(S.CITY, ' ', S.STREET_ADDRESS1, ' ', S.STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(S.TLNO, 3), '-', SUBSTR(S.TLNO, 4, 4), '-', SUBSTR(S.TLNO, 8, 4)) AS '전화번호'
FROM TARGET_USER AS F LEFT JOIN USED_GOODS_USER AS S ON F.WRITER_ID = S.USER_ID
ORDER BY S.USER_ID DESC