WITH REST_REVIEW_AVG_SCORE AS (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
)

SELECT F.REST_ID, F.REST_NAME, F.FOOD_TYPE, F.FAVORITES, F.ADDRESS, S.SCORE
FROM REST_INFO AS F JOIN REST_REVIEW_AVG_SCORE AS S ON F.REST_ID = S.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY S.SCORE DESC, F.FAVORITES DESC