# SELECT COUNT(F.ID) AS FISH_COUNT, S.FISH_NAME
# FROM FISH_NAME_INFO AS S
# LEFT JOIN FISH_INFO AS F ON S.FISH_TYPE = F.FISH_TYPE
# GROUP BY S.FISH_TYPE, S.FISH_NAME
# ORDER BY FISH_COUNT DESC;

SELECT COUNT(*) AS FISH_COUNT, S.FISH_NAME
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS S ON F.FISH_TYPE = S.FISH_TYPE
GROUP BY S.FISH_NAME, F.FISH_TYPE -- 이름과 타입을 묶어서 그룹화
ORDER BY FISH_COUNT DESC;