WITH IS_USED AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE('20221016') AND DATE('20221016') <= END_DATE
)

SELECT C.CAR_ID,
    CASE
        WHEN C.CAR_ID IN (SELECT CAR_ID FROM IS_USED) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC