WITH CAR_RENTAL_COMPANY_INFO AS (
    SELECT S.HISTORY_ID, S.CAR_ID, DATEDIFF(S.END_DATE, S.START_DATE) + 1 AS DURATION, F.DAILY_FEE,
        CASE
        WHEN DATEDIFF(S.END_DATE, S.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(S.END_DATE, S.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(S.END_DATE, S.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS F
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS S ON F.CAR_ID = S.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT F.HISTORY_ID, ROUND(F.DURATION * F.DAILY_FEE * (100 - IFNULL(S.DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_INFO AS F
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS S ON F.DURATION_TYPE = S.DURATION_TYPE AND S.CAR_TYPE = '트럭'
ORDER BY FEE DESC, F.HISTORY_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '트럭'