# WITH TEMP AS (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
#     GROUP BY CAR_ID
#     HAVING COUNT(CAR_ID) >= 5
# )

# SELECT MONTH(S.START_DATE) AS MONTH, S.CAR_ID, COUNT(S.CAR_ID) AS RECORDS
# FROM TEMP AS F JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS S ON F.CAR_ID = S.CAR_ID
# GROUP BY MONTH, S.CAR_ID
# ORDER BY MONTH ASC, S.CAR_ID DESC

-- 1. 8~10월 총 대여 횟수가 5회 이상인 자동차 ID 리스트 뽑기
WITH TARGET_CARS AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

-- 2. 위 리스트에 속한 자동차들의 월별 기록 산출
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM TARGET_CARS)
  AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;