WITH TEMP AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAXI, YEAR(DIFFERENTIATION_DATE) AS DATE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (T.MAXI - E.SIZE_OF_COLONY)  AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA AS E
LEFT JOIN TEMP AS T ON YEAR(E.DIFFERENTIATION_DATE) = T.DATE
ORDER BY YEAR, YEAR_DEV