

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        ABS(SIZE_OF_COLONY - (SELECT MAX(SIZE_OF_COLONY) 
                              FROM ECOLI_DATA
                              WHERE YEAR = YEAR(DIFFERENTIATION_DATE))) AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV