WITH TEMP AS(
    SELECT COUNT(*) AS FISH_COUNT
    FROM FISH_INFO AS F JOIN FISH_NAME_INFO AS S ON F.FISH_TYPE = S.FISH_TYPE
    WHERE S.FISH_NAME IN ('BASS', 'SNAPPER')
    GROUP BY S.FISH_TYPE
)

SELECT SUM(FISH_COUNT) AS FISH_COUNT
FROM TEMP