SELECT F.ID, S.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F JOIN FISH_NAME_INFO AS S ON F.FISH_TYPE = S.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY F.ID