WITH TEMP AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAXI
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT T.ID, N.FISH_NAME, T.LENGTH
FROM FISH_INFO AS T
JOIN FISH_NAME_INFO AS N ON T.FISH_TYPE = N.FISH_TYPE
JOIN TEMP ON T.FISH_TYPE = TEMP.FISH_TYPE AND T.LENGTH = TEMP.MAXI
ORDER BY T.ID