SELECT CONCAT('/home/grep/src/', S.BOARD_ID, '/', S.FILE_ID, S.FILE_NAME, S.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS F JOIN USED_GOODS_FILE AS S ON F.BOARD_ID = S.BOARD_ID
WHERE F.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY S.FILE_ID DESC