WITH PROCESSED_FISH_INFO AS (
    SELECT ID, FISH_TYPE,
    CASE
    WHEN LENGTH IS NULL THEN 10
    ELSE LENGTH
    END AS LENGTH,
    TIME
    FROM FISH_INFO
) 
,TARGET_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM PROCESSED_FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(LENGTH) >= 33
)

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM PROCESSED_FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM TARGET_FISH)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE